'use strict';

const DEPLOYMENT_STATES = {
  STABLE: 'STABLE',
  DEPLOYING: 'DEPLOYING',
  SCALING: 'SCALING',
};

const PRIMARY_DEPLOYMENT_STATUS = 'PRIMARY';

module.exports = {
  DEPLOYMENT_STATES,
  PRIMARY_DEPLOYMENT_STATUS,
};
