'use strict';

const DEPLOYMENT_STATES = {
  STABLE: 'STABLE',
  DEPLOYING: 'DEPLOYING',
  SCALING: 'SCALING',
  RECOVER: 'RECOVER',
};

const PRIMARY_DEPLOYMENT_STATUS = 'PRIMARY';

const AWS_API_VERSION = '2014-11-13';

module.exports = {
  DEPLOYMENT_STATES,
  PRIMARY_DEPLOYMENT_STATUS,
  AWS_API_VERSION,
};
